#!/bin/bash

#PBS -N racing-sim
#PBS -j oe
#PBS -o output/topic-modelling.out
#PBS -q clxq
#PBS -l walltime=24:00:00

# Change the working directory (default is home directory)
cd "$PBS_O_WORKDIR"

echo "Running on host: $(hostname)"
echo "Time is: $(date)"
echo "Directory is: $(pwd)"
echo "PBS job ID is: $PBS_JOBID"
echo "This jobs runs on the following machines: $(cat "$PBS_NODEFILE" | uniq)"
echo

# Run the executable
python3.6 topic-modelling.py
